apiRules:
  - include:
      uidRegex: ^softtissue\.Camera
      type: Namespace
  - include:
      uidRegex: ^softtissue\.Carton
      type: Namespace
  - include:
      uidRegex: ^softtissue\.Character
      type: Namespace
  - exclude:
      uidRegex: ^softtissue\._KittenRhythm
      type: Namespace
  - exclude:
      uidRegex: .*
      type: Namespace
